//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aw_hecsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_contribuyentes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_contribuyentes()
        {
            this.inf_contacto_contribuyente = new HashSet<inf_contacto_contribuyente>();
        }
    
        public System.Guid id_contribuyente { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public Nullable<int> id_tipo_rfc { get; set; }
        public string rfc { get; set; }
        public string razon_social { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string callenum { get; set; }
        public Nullable<int> id_codigo { get; set; }
        public string codigo_contribuyente { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public System.Guid id_empresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_contacto_contribuyente> inf_contacto_contribuyente { get; set; }
        public virtual inf_empresa inf_empresa { get; set; }
    }
}
